const carName = "BMW";
let maxCarSpeed = "290";
maxCarSpeed = "400";
console.log("У вас поменялась скорость", maxCarSpeed);
let carOwner = "";
carOwner = "Санек";
console.log("Поменялся владелец", carOwner);
alert(carName);
alert(maxCarSpeed);
alert(carOwner);
